### ISSUE TITLE
kwin support

### ISSUE THREAD

**Issue by KottV** [SeeLook/BespinQt5#1]
Hi!

Just found your port. Could it be possible to make kf5 version of kwin deco? You know, that is great and only one (afaik) that supports side decoration placement.

**Comment by SeeLook** [comment]
Hi
Rather I'm too small for it....
As long as I had experience in switching from Qt4 to Qt5, all that style affairs are quite different realm.
So this port doesn't work well because it needs more review of style code. I tried to use it for some time but I gave up. I accepted flat word :-)
Almost two years passed since I ported it and You are first person interested in it.

**Comment by KottV** [comment]
Well, thank you anyway :)
